name: linux

on:
  workflow_dispatch:

jobs:
  ubuntu1604:
    runs-on: ubuntu-16.04

    env:
      ONNX_VERSION: v1.7.0
      SHARED_PKG_NAME: onnxruntime-1.7.0-ubuntu1604-shared
      STATIC_PKG_NAME: onnxruntime-1.7.0-ubuntu1604-static

    steps:
      # 检出代码
      - uses: actions/checkout@v2

      # 检出onnxruntime
      - name: checkout onnxruntime
        uses: actions/checkout@v2
        with:
          repository: microsoft/onnxruntime
          path: onnxruntime-${{ env.ONNX_VERSION }}
          ref: ${{ env.ONNX_VERSION }}
          submodules: recursive

      # 复制编译脚本
      - name: copy build script
        run: |
          cp build-onnxruntime.sh onnxruntime-${{ env.ONNX_VERSION }}
          cp onnxruntime_cmake_options.txt onnxruntime-${{ env.ONNX_VERSION }}

      # 编译
      - name: build
        run: |
          cd onnxruntime-${{ env.ONNX_VERSION }}
          chmod a+x build-onnxruntime.sh &&./build-onnxruntime.sh

      # install文件夹改名linux，并使用7z压缩
      - name: 7zip
        run: |
          mv onnxruntime-${{ env.ONNX_VERSION }}/build/Linux/Release/install linux
          7z a ${{ env.SHARED_PKG_NAME }}.7z linux
          rm -r -f linux
          mv onnxruntime-${{ env.ONNX_VERSION }}/build/Linux/Release/install-static linux
          7z a ${{ env.STATIC_PKG_NAME }}.7z linux
          rm -r -f linux

      # 上传artifact
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.SHARED_PKG_NAME }}
          path: ${{ env.SHARED_PKG_NAME }}.7z

      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.STATIC_PKG_NAME }}
          path: ${{ env.STATIC_PKG_NAME }}.7z